ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-debian-python

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install RPi.GPIO
RUN pip3 install requests gpiozero paho-mqtt
COPY . .


CMD ["python3", "app.py"]
